# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8cfb30aaa7bff9111688f04855080f741216228844bd15950111d9267a53e66c0d4a017e7f498831345475d298b55f93a37dd97ff12c35b404b1c68dcacda26

test:
  secret_key_base: 7ff11f84266bd287104d80441c99b3a378fb48b86a329d5003e9f90851a3e65a59b3510afedc77045d0db738f281a6fe08a8e208ffdeecabfa8fb7d33132eb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
